server:
  port: 8085
spring:
  datasource:
    url: "jdbc:h2:./restdb"
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true

  application:
    name: APP1

eureka:
  client:
    register-with-eureka: true
  service-url: http://localhost:8761/eureka/
